baseURL = "https://blog.vghaisas.com/"
languageCode = "en-us"
title = "Bit Nebula"
theme = "hyde-like"

Copyright = '© 2017 Vivek Ghaisas. <a href="https://blog.vghaisas.com/license">License</a>'

GoogleAnalytics = "UA-88441640-2"

PygmentsCodeFences = true
pygmentsuseclasses = true

[Permalinks]
    post = "/:filename/"

[Params]
    Author = "Vivek Ghaisas"
    Description = "A blog with some stuff.<br>— Vivek Ghaisas"
    DisqusShortname = "bitnebula"

[[menu.main]]
    name = "vghaisas.com"
    url = "https://vghaisas.com"
    weight = 10
